version: '3.7'

services:
  db:
    image: 'postgres:11.5-alpine'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      -  54321:5432
    volumes:
      - 'db:/var/lib/postgresql/data'
    networks:
      - lite

  app:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b 0.0.0.0"
    tty: true
    stdin_open: true
    tmpfs:
      - /tmp
    ports:
      - 3000:3000
    volumes:
      - bundle_core:/bundle
      - .:/app
      - storage:/app/storage
      - cache:/cache # Added to support Windows 10 Docker
    environment:
      - SPROCKETS_CACHE=/cache # Added to support Windows 10 Docker
    depends_on:
      - db
    networks:
      - lite

volumes:
  db:
  bundle_core:
  storage:
  cache: # Added to support Windows 10 Docker

networks:
  lite:
    driver: bridge
