---
development:
  cloud_name: da84twcxv
  api_key: '729392473934592'
  api_secret: fxBROXJ698D0ipJ6VAgRhUAwPMQ
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: da84twcxv
  api_key: '729392473934592'
  api_secret: fxBROXJ698D0ipJ6VAgRhUAwPMQ
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: da84twcxv
  api_key: '729392473934592'
  api_secret: fxBROXJ698D0ipJ6VAgRhUAwPMQ
  enhance_image_tag: true
  static_file_support: false
