---
development:
  cloud_name: hel88
  api_key: '846496373843319'
  api_secret: miLbJ5poQQbig-jnww055HXaUXw
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: hel88
  api_key: '846496373843319'
  api_secret: miLbJ5poQQbig-jnww055HXaUXw
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: hel88
  api_key: '846496373843319'
  api_secret: miLbJ5poQQbig-jnww055HXaUXw
  enhance_image_tag: true
  static_file_support: false
